### PR TITLE
No newline at end of file

### PR DESCRIPTION
**Pull request by hackebrot**
Resolve an issue with strings that don't end in a newline, see https://github.com/audreyr/cookiecutter/pull/917.

### CODE REVIEW

**Comment by hackebrot** [comment]
Can you please have a look at this when you're free @pydanny @michaeljoseph, please? 🍪

**Comment by pydanny** [comment]
Yay code!

**Comment by hackebrot** [comment]
Thanks @pydanny! 🙇

**Comment by mikeckennedy** [comment]
Nice to see this fixed guys, thanks for working with me on it!

**Pull request merged**
